/**
 * Fixtures da prévia demonstrativa.
 *
 * Isoladas aqui porque não são do produto: sem `.env.local` ou sem sessão, a interface
 * mostra estes dados fabricados e se identifica como prévia.
 *
 * ISTO É ANDAIME. O modo prévia existe porque não há como criar uma empresa pela
 * interface — a única forma hoje é rodar SQL à mão. Quando a Etapa 5 entregar o
 * onboarding, esta pasta inteira deve ser APAGADA, não mantida.
 */

import type { PatioOrder } from "@boramarca/core";

const day = "2026-08-24T12:00:00.000Z";

export const demonstrationOrders: PatioOrder[] = [
  {
    id: "demo-001",
    tenant_id: "demo-tenant",
    number: 318,
    status: "awaiting_service",
    created_at: day,
    received_at: "2026-08-24T11:20:00.000Z",
    customer_id: "demo-customer-1",
    customer_name: "Mariana Nunes",
    vehicle_id: "demo-vehicle-1",
    license_plate: "RUE-4K29",
    normalized_license_plate: "RUE4K29",
    make: "Jeep",
    model: "Compass",
    color: "Cinza",
    professional_id: "demo-professional-1",
    professional_name: "Caio",
    box_id: "demo-box-1",
    box_code: "B02",
    box_name: "Box 02",
    total_amount: 320,
    paid_amount: 0,
    outstanding_amount: 320,
    payment_status: "unpaid",
  },
  {
    id: "demo-002",
    tenant_id: "demo-tenant",
    number: 317,
    status: "in_service",
    created_at: day,
    received_at: "2026-08-24T10:40:00.000Z",
    customer_id: "demo-customer-2",
    customer_name: "Gustavo Lima",
    vehicle_id: "demo-vehicle-2",
    license_plate: "FAN-7A41",
    normalized_license_plate: "FAN7A41",
    make: "Toyota",
    model: "Corolla Cross",
    color: "Preto",
    professional_id: "demo-professional-2",
    professional_name: "Nina",
    box_id: "demo-box-2",
    box_code: "B01",
    box_name: "Box 01",
    total_amount: 480,
    paid_amount: 240,
    outstanding_amount: 240,
    payment_status: "partial",
  },
  {
    id: "demo-003",
    tenant_id: "demo-tenant",
    number: 315,
    status: "service_completed",
    created_at: day,
    received_at: "2026-08-24T09:10:00.000Z",
    customer_id: "demo-customer-3",
    customer_name: "Juliana Prado",
    vehicle_id: "demo-vehicle-3",
    license_plate: "SMK-2D84",
    normalized_license_plate: "SMK2D84",
    make: "BMW",
    model: "320i",
    color: "Branco",
    professional_id: "demo-professional-3",
    professional_name: "Icaro",
    box_id: "demo-box-3",
    box_code: "B03",
    box_name: "Box 03",
    total_amount: 690,
    paid_amount: 690,
    outstanding_amount: 0,
    payment_status: "paid",
  },
  {
    id: "demo-004",
    tenant_id: "demo-tenant",
    number: 312,
    status: "awaiting_pickup",
    created_at: day,
    received_at: "2026-08-24T08:25:00.000Z",
    customer_id: "demo-customer-4",
    customer_name: "Roberto Alves",
    vehicle_id: "demo-vehicle-4",
    license_plate: "SJU-9L13",
    normalized_license_plate: "SJU9L13",
    make: "Volkswagen",
    model: "T-Cross",
    color: "Azul",
    professional_id: "demo-professional-1",
    professional_name: "Caio",
    box_id: null,
    box_code: null,
    box_name: null,
    total_amount: 210,
    paid_amount: 210,
    outstanding_amount: 0,
    payment_status: "paid",
  },
];
